// See default config https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js
module.exports = {
  theme: {
    fontFamily: {
      'title': 'Nunito, -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol',
      'body': 'Open Sans, -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol',
    },
    fontSize: {
      'xs': '10px',
      'sm': '12px',
      'base': '14px',
      'lg': '16px',
      'xl': '18px',
      '2xl': '20px',
      '3xl': '24px',
      '4xl': '32px',
      '5xl': '42px',
    },
    borderRadius: {
      'none': '0',
      'px': '1px',
      'sm': '2px',
      default: '4px',
      'lg': '8px',
      'xl': '16px',
    },
    screens: {
      'tablet': '900px',
    },
    extend: {
      padding: {
        px: '1px',
        xs: '2px',
        sm: '4px',
        '0': '0',
        '1': '8px',
        '1-1/2': '12px',
        '2': '16px',
        '3': '24px',
        '4': '32px',
        '5': '40px',
        '6': '48px',
        '7': '56px',
        '8': '64px',
        '9': '72px',
        '16': '128px',
      },
      margin: {
        auto: 'auto',
        px: '1px',
        xs: '2px',
        sm: '4px',
        '0': '0',
        '1': '8px',
        '1-1/2': '12px',
        '2': '16px',
        '3': '24px',
        '4': '32px',
        '5': '40px',
        '6': '48px',
        '7': '56px',
        '8': '64px',
        '9': '72px',
        '16': '128px',
      },
    },
  },
  variants: {}
}
